apiVersion: v1
kind: Service
metadata:
  name: apm-server
  namespace: monitoring
  labels:
    app: apm-server
spec:
  selector:
    app: apm-server
  ports:
  - port: 8200
    targetPort: 8200
    name: http