apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: patient-monitoring
data:
  # API Gateway Configuration
  API_GATEWAY_PORT: "3000"
  
  # Patient Service Configuration
  PATIENT_SERVICE_PORT: "3001"
  
  # Vitals Ingestion Service Configuration
  VITALS_INGESTION_SERVICE_PORT: "3002"
  
  # Vitals Processing Service Configuration
  VITALS_PROCESSING_SERVICE_PORT: "3003"
  
  # Alert Service Configuration
  ALERT_SERVICE_PORT: "3004"
  
  # Notification Service Configuration
  NOTIFICATION_SERVICE_PORT: "3005"
  
  # RabbitMQ Configuration
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"
  RABBITMQ_MANAGEMENT_PORT: "15672"
  
  # Database Configuration
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  TIMESCALEDB_HOST: "timescaledb"
  TIMESCALEDB_PORT: "5432"
  
  # Vitals Queue Names
  QUEUE_VITALS_RAW: "vitals.raw"
  QUEUE_VITALS_PROCESSED: "vitals.processed"
  QUEUE_ALERTS_NEW: "alerts.new"
  QUEUE_NOTIFICATIONS_OUTBOUND: "notifications.outbound"
  
  # Logging Configuration
  LOG_LEVEL: "info"