apiVersion: v1
kind: ConfigMap
metadata:
  name: metricbeat-config
  namespace: monitoring
data:
  metricbeat.yml: |
    metricbeat.config.modules:
      path: ${path.config}/modules.d/*.yml
      reload.enabled: false

    metricbeat.modules:
    - module: system
      period: 10s
      metricsets:
        - cpu
        - load
        - memory
        - network
        - process
        - process_summary
        - uptime
        - socket_summary
      processes: ['.*']
      process.include_top_n:
        by_cpu: 5
        by_memory: 5
      
    - module: system
      period: 1m
      metricsets:
        - filesystem
        - fsstat
      processors:
      - drop_event.when.regexp:
          system.filesystem.mount_point: '^/(sys|cgroup|proc|dev|etc|host|lib|snap)($|/)'
    
    - module: docker
      period: 10s
      hosts: ["unix:///var/run/docker.sock"]
      metricsets:
        - container
        - cpu
        - diskio
        - memory
        - network
      
    - module: kubernetes
      period: 10s
      node: ${NODE_NAME}
      hosts: ["https://${NODE_NAME}:10250"]
      metricsets:
        - node
        - system
        - pod
        - container
        - volume
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      ssl.verification_mode: "none"
    
    processors:
      - add_cloud_metadata: ~
      - add_host_metadata: ~
      - add_kubernetes_metadata:
          host: ${NODE_NAME}
          matchers:
          - logs_path:
              logs_path: "/var/log/containers/"

    output.elasticsearch:
      hosts: ["elasticsearch-api:9200"]
      index: "metricbeat-%{+yyyy.MM.dd}"
      
    logging.level: info
    logging.to_files: true
    logging.files:
      path: /var/log/metricbeat
      name: metricbeat
      keepfiles: 7
      permissions: 0644

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metricbeat-kube-state-config
  namespace: monitoring
data:
  metricbeat.yml: |
    metricbeat.config.modules:
      path: ${path.config}/modules.d/*.yml
      reload.enabled: false

    metricbeat.modules:
    - module: kubernetes
      period: 10s
      metricsets:
        - state_node
        - state_deployment
        - state_replicaset
        - state_pod
        - state_container
      hosts: ["kube-state-metrics:8080"]
    
    processors:
      - add_cloud_metadata: ~
      - add_host_metadata: ~

    output.elasticsearch:
      hosts: ["elasticsearch-api:9200"]
      index: "metricbeat-%{+yyyy.MM.dd}"
      
    logging.level: info
    logging.to_files: true
    logging.files:
      path: /var/log/metricbeat
      name: metricbeat
      keepfiles: 7
      permissions: 0644