apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: monitoring
  labels:
    app: logstash
spec:
  selector:
    app: logstash
  ports:
  - port: 5044
    name: beats
    targetPort: 5044
  - port: 9600
    name: api
    targetPort: 9600