apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-service
  namespace: patient-monitoring
spec:
  replicas: 2
  selector:
    matchLabels:
      app: alert-service
  template:
    metadata:
      labels:
        app: alert-service
    spec:
      containers:
      - name: alert-service
        image: ${REGISTRY}/alert-service:latest
        ports:
        - containerPort: 3004
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: ALERT_SERVICE_PORT
        - name: NODE_ENV
          value: "production"
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: POSTGRES_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: POSTGRES_PORT
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: POSTGRES_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: POSTGRES_PASSWORD
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: POSTGRES_DB
        - name: RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: RABBITMQ_HOST
        - name: RABBITMQ_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: RABBITMQ_PORT
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: RABBITMQ_USER
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: RABBITMQ_PASSWORD
        - name: QUEUE_VITALS_PROCESSED
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: QUEUE_VITALS_PROCESSED
        - name: QUEUE_ALERTS_NEW
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: QUEUE_ALERTS_NEW
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: LOG_LEVEL
        resources:
          requests:
            cpu: "0.3"
            memory: "256Mi"
          limits:
            cpu: "0.6"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 3004
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3004
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: alert-service
  namespace: patient-monitoring
spec:
  selector:
    app: alert-service
  ports:
  - port: 3004
    targetPort: 3004