apiVersion: apps/v1
kind: Deployment
metadata:
  name: vitals-processing-service
  namespace: patient-monitoring
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vitals-processing-service
  template:
    metadata:
      labels:
        app: vitals-processing-service
    spec:
      containers:
      - name: vitals-processing-service
        image: ${REGISTRY}/vitals-processing-service:latest
        ports:
        - containerPort: 3003
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: VITALS_PROCESSING_SERVICE_PORT
        - name: NODE_ENV
          value: "production"
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: TIMESCALEDB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: TIMESCALEDB_PORT
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: TIMESCALEDB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: TIMESCALEDB_PASSWORD
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: TIMESCALEDB_DB
        - name: RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: RABBITMQ_HOST
        - name: RABBITMQ_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: RABBITMQ_PORT
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: RABBITMQ_USER
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: RABBITMQ_PASSWORD
        - name: QUEUE_VITALS_RAW
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: QUEUE_VITALS_RAW
        - name: QUEUE_VITALS_PROCESSED
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: QUEUE_VITALS_PROCESSED
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: LOG_LEVEL
        resources:
          requests:
            cpu: "0.3"
            memory: "512Mi"
          limits:
            cpu: "0.8"
            memory: "1Gi"
        livenessProbe:
          httpGet:
            path: /health
            port: 3003
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3003
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: vitals-processing-service
  namespace: patient-monitoring
spec:
  selector:
    app: vitals-processing-service
  ports:
  - port: 3003
    targetPort: 3003