apiVersion: apps/v1
kind: Deployment
metadata:
  name: vitals-ingestion-service
  namespace: patient-monitoring
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vitals-ingestion-service
  template:
    metadata:
      labels:
        app: vitals-ingestion-service
    spec:
      containers:
      - name: vitals-ingestion-service
        image: ${REGISTRY}/vitals-ingestion-service:latest
        ports:
        - containerPort: 3002
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: VITALS_INGESTION_SERVICE_PORT
        - name: NODE_ENV
          value: "production"
        - name: RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: RABBITMQ_HOST
        - name: RABBITMQ_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: RABBITMQ_PORT
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: RABBITMQ_USER
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: RABBITMQ_PASSWORD
        - name: QUEUE_VITALS_RAW
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: QUEUE_VITALS_RAW
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: LOG_LEVEL
        resources:
          requests:
            cpu: "0.3"
            memory: "256Mi"
          limits:
            cpu: "0.6"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: vitals-ingestion-service
  namespace: patient-monitoring
spec:
  selector:
    app: vitals-ingestion-service
  ports:
  - port: 3002
    targetPort: 3002