apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-patients-pv
  namespace: pms
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /data/postgres-patients
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-patients-pvc
  namespace: pms
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard