version: '3.8'

services:
  patient-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: patient-service
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=patient_service
      - DB_HOST=postgres
      - DB_PORT=5432
      - LOG_LEVEL=info
    depends_on:
      - postgres
    networks:
      - patient-monitoring

  postgres:
    image: postgres:14-alpine
    container_name: patient-service-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=patient_service
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - patient-monitoring

networks:
  patient-monitoring:
    name: patient-monitoring
    driver: bridge

volumes:
  postgres-data: